//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/application/crossLayerMsg/CrossLayerMsg.msg.
//

#ifndef _CROSSLAYERMSG_M_H_
#define _CROSSLAYERMSG_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Enum generated from <tt>src/node/application/crossLayerMsg/CrossLayerMsg.msg:1</tt> by nedtool.
 * <pre>
 * enum CrossLayerCommandDef
 * {
 * 
 *     TAXAMAC_INFO = 1;
 *     BUFFER_INFO = 2;
 * }
 * </pre>
 */
enum CrossLayerCommandDef {
    TAXAMAC_INFO = 1,
    BUFFER_INFO = 2
};

/**
 * Class generated from <tt>src/node/application/crossLayerMsg/CrossLayerMsg.msg:6</tt> by nedtool.
 * <pre>
 * message CrossLayerMsg
 * {
 *     int type @enum(CrossLayerCommandDef);
 *     double taxaMAC = 0;
 *     double bufferState = 0;
 * }
 * </pre>
 */
class CrossLayerMsg : public ::cMessage
{
  protected:
    int type_var;
    double taxaMAC_var;
    double bufferState_var;

  private:
    void copy(const CrossLayerMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CrossLayerMsg&);

  public:
    CrossLayerMsg(const char *name=NULL, int kind=0);
    CrossLayerMsg(const CrossLayerMsg& other);
    virtual ~CrossLayerMsg();
    CrossLayerMsg& operator=(const CrossLayerMsg& other);
    virtual CrossLayerMsg *dup() const {return new CrossLayerMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getType() const;
    virtual void setType(int type);
    virtual double getTaxaMAC() const;
    virtual void setTaxaMAC(double taxaMAC);
    virtual double getBufferState() const;
    virtual void setBufferState(double bufferState);
};

inline void doPacking(cCommBuffer *b, CrossLayerMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, CrossLayerMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef _CROSSLAYERMSG_M_H_

