//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/application/throughputPriority/ThroughputPriorityMsg.msg.
//

#ifndef _THROUGHPUTPRIORITYMSG_M_H_
#define _THROUGHPUTPRIORITYMSG_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Enum generated from <tt>src/node/application/throughputPriority/ThroughputPriorityMsg.msg:1</tt> by nedtool.
 * <pre>
 * enum ThroughputPriorityCommandDef
 * {
 * 
 *     TAXAMAC_INFO = 1;
 *     BUFFER_INFO = 2;
 * }
 * </pre>
 */
enum ThroughputPriorityCommandDef {
    TAXAMAC_INFO = 1,
    BUFFER_INFO = 2
};

/**
 * Class generated from <tt>src/node/application/throughputPriority/ThroughputPriorityMsg.msg:6</tt> by nedtool.
 * <pre>
 * message ThroghputPriorityMsg
 * {
 *     int type @enum(ThroughputPriorityCommandDef);
 *     double taxaMAC = 0;
 *     double bufferState = 0;
 * }
 * </pre>
 */
class ThroghputPriorityMsg : public ::cMessage
{
  protected:
    int type_var;
    double taxaMAC_var;
    double bufferState_var;

  private:
    void copy(const ThroghputPriorityMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ThroghputPriorityMsg&);

  public:
    ThroghputPriorityMsg(const char *name=NULL, int kind=0);
    ThroghputPriorityMsg(const ThroghputPriorityMsg& other);
    virtual ~ThroghputPriorityMsg();
    ThroghputPriorityMsg& operator=(const ThroghputPriorityMsg& other);
    virtual ThroghputPriorityMsg *dup() const {return new ThroghputPriorityMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getType() const;
    virtual void setType(int type);
    virtual double getTaxaMAC() const;
    virtual void setTaxaMAC(double taxaMAC);
    virtual double getBufferState() const;
    virtual void setBufferState(double bufferState);
};

inline void doPacking(cCommBuffer *b, ThroghputPriorityMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ThroghputPriorityMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef _THROUGHPUTPRIORITYMSG_M_H_

