//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/application/throughputTest2/ThroughputTestControl2.msg.
//

#ifndef _THROUGHPUTTESTCONTROL2_M_H_
#define _THROUGHPUTTESTCONTROL2_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Enum generated from <tt>src/node/application/throughputTest2/ThroughputTestControl2.msg:1</tt> by nedtool.
 * <pre>
 * enum ThroughputTest2CommandDef
 * {
 * 
 *     SET_RATE = 1;
 *     SET_PRIORITY = 2;
 * }
 * </pre>
 */
enum ThroughputTest2CommandDef {
    SET_RATE = 1,
    SET_PRIORITY = 2
};

/**
 * Class generated from <tt>src/node/application/throughputTest2/ThroughputTestControl2.msg:6</tt> by nedtool.
 * <pre>
 * message ThroughputTest2ControlCommand
 * {
 *     int throughputTestCommandKind @enum(ThroughputTest2CommandDef);
 *     double parameter = 0;
 * }
 * </pre>
 */
class ThroughputTest2ControlCommand : public ::cMessage
{
  protected:
    int throughputTestCommandKind_var;
    double parameter_var;

  private:
    void copy(const ThroughputTest2ControlCommand& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ThroughputTest2ControlCommand&);

  public:
    ThroughputTest2ControlCommand(const char *name=NULL, int kind=0);
    ThroughputTest2ControlCommand(const ThroughputTest2ControlCommand& other);
    virtual ~ThroughputTest2ControlCommand();
    ThroughputTest2ControlCommand& operator=(const ThroughputTest2ControlCommand& other);
    virtual ThroughputTest2ControlCommand *dup() const {return new ThroughputTest2ControlCommand(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getThroughputTestCommandKind() const;
    virtual void setThroughputTestCommandKind(int throughputTestCommandKind);
    virtual double getParameter() const;
    virtual void setParameter(double parameter);
};

inline void doPacking(cCommBuffer *b, ThroughputTest2ControlCommand& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ThroughputTest2ControlCommand& obj) {obj.parsimUnpack(b);}


#endif // ifndef _THROUGHPUTTESTCONTROL2_M_H_

